source 'https://rubygems.org'
gem 'jemoji',                   '~> 0.7.0'
gem 'sanitize',                 '~> 4.4.0'
gem 'bootstrap-sass'
gem 'mini_magick'
gem 'uglifier'
gem 'sprockets'
gem 'sprockets-es6'
gem 'html-proofer'

group :jekyll_plugins do
  gem 'jekyll-gist',              '~> 1.4'
  gem 'jekyll-assets',            '~> 2.2.8'
  gem 'jekyll-sitemap',           '~> 0.12.0'
  gem 'jekyll-seo-tag',           '~> 2.0'
  gem 'jekyll-mentions',          '~> 1.2.0'
  gem 'jekyll-github-metadata',   '~> 2.1.1'
  gem 'algoliasearch-jekyll',     '~> 0.8.0'
  #gem 'algoliasearch-jekyll',     '~> 1.0.0.beta.pre.1'
end
