source 'https://rubygems.org'
gem 'jekyll', '~> 3.6'
gem 'jemoji'
gem 'mini_magick'
gem 'uglifier'
gem 'sprockets'
gem 'sprockets-es6'
gem 'html-proofer'
gem 'jekyll-last-modified-at'
gem 'jekyll-feed'
gem 'jekyll-avatar'
gem 'jekyll-tagging'
gem 'jekyll-toc'
gem 'jekyll-relative-links'
gem 'jekyll-git_metadata'
gem 'jekyll-github-metadata'
gem 'json'
gem 'geokit'
gem 'rouge'


group :jekyll_plugins do
  gem 'jekyll-gist'
  gem 'jekyll-assets'
  gem 'jekyll-sitemap'
  gem 'jekyll-mentions'
  gem 'jekyll-algolia'
  gem 'jekyll-contentblocks'
  gem 'jekyll-timeago'
  gem 'jekyll-giphy'
end
