#!/bin/bash
set -e # halt script on error

git clone https://${DEPLOY_TOKEN}@${GITHUB_REPO} --branch gh-pages _site

bundle exec jekyll build
# bundle exec htmlproofer ./_site --disable-external --allow-hash-href 
