#!/bin/bash

# Jekyll's output folder
cd _site/

# Configure github properties
git init
git config user.name "Travis CI"
git config user.email ${EMAIL}

# Commit and Push content
git add .
git commit -m "Deployed using Travis CI - Build: $TRAVIS_BUILD_NUMBER"

# push to repo and prevents any sensitive data from printing on the console.
git push "https://${DEPLOY_TOKEN}@${GITHUB_REPO}" HEAD:${GITHUB_REPO_BRANCH}
