// Gets converted to _W
Weebly = window.Weebly || {};
Weebly.templates = {
		'search/filter/search-facet-color': "<li class=\"wsite-search-facet wsite-search-facet-color\">\n\t<h3>{{facet_name}}<\/h3>\n\t<form name=\"{{column_name}}\">\n\t\t<ul class=\"wsite-search-facet-entries clearfix\">\n\t\t\t{{#facet_entries}}\n\t\t\t\t<li>\n\t\t\t\t\t<label title=\"{{name}}\" style=\"background-color:{{display_value}};\" {{#active}}class=\"active\"{{\/active}}>\n\t\t\t\t\t\t<input type=\"checkbox\" class=\"w-input-offscreen\" name=\"{{filter_text}}\" value=\"1\" tabindex=\"-1\" \/>\n\t\t\t\t\t<\/label>\n\t\t\t\t<\/li>\n\t\t\t{{\/facet_entries}}\n\t\t<\/ul>\n\t<\/form>\n<\/li>\n",
		'search/filter/search-facet-checkbox': "<li class=\"wsite-search-facet wsite-search-facet-checkbox\">\n\t<h3>{{facet_name}}<\/h3>\n\t<form name=\"{{column_name}}\">\n\t\t<ul class=\"wsite-search-facet-entries\">\n\t\t\t{{#facet_entries}}\n\t\t\t\t<li>\n\t\t\t\t\t<label>\n\t\t\t\t\t\t<input type=\"checkbox\" name=\"{{filter_text}}\" value=\"1\" \/><!--\n\t\t\t\t\t\t{{! Commenting 'hack' to remove spaces }}\n\t\t\t\t\t\t--><a> {{! These aren't real links, used to use theme colors }}\n\t\t\t\t\t\t\t{{display_value}}\n\t\t\t\t\t\t\t<span class=\"count\">(<span class=\"count-inner\">{{count}}<\/span>)<\/span>\n\t\t\t\t\t\t<\/a>\n\t\t\t\t\t<\/label>\n\t\t\t\t<\/li>\n\t\t\t{{\/facet_entries}}\n\t\t<\/ul>\n\t<\/form>\n<\/li>\n",
		'search/filter/search-facet-price': "<li class=\"wsite-search-facet wsite-search-facet-price\">\n\t<h3>{{#tl}}Price{{\/tl}}<\/h3>\n\t<form name=\"{{column_name}}\">\n\t\t<input type=\"text\" class=\"wsite-form-input\" name=\"lowprice\" pattern=\"[0-9]*\" placeholder=\"&mdash;\" value=\"{{lowprice}}\" \/><!--\n\t\t{{! Commenting 'hack' to get inline-block to not have spaces }}\n\t\t--><span>{{#tl}}to{{\/tl}}<\/span><!--\n\t\t{{! Commenting 'hack' to get inline-block to not have spaces }}\n\t\t--><input type=\"text\" class=\"wsite-form-input\" name=\"highprice\" pattern=\"[0-9]*\" placeholder=\"&mdash;\" value=\"{{highprice}}\" \/>\n\t<\/form>\n<\/li>\n",
		'search/filter/search-facet-availability': "<li class=\"wsite-search-facet wsite-search-facet-availability\">\n\t<h3>{{#tl}}Availability{{\/tl}}<\/h3>\n\t<form name=\"availability-facet\">\n\t\t<ul class=\"wsite-search-facet-entries\">\n\t\t\t<li>\n\t\t\t\t<label>\n\t\t\t\t\t<input type=\"checkbox\" name=\"outofstock\" value=\"1\" \/><!--\n\t\t\t\t\t{{! Commenting 'hack' to remove spaces }}\n\t\t\t\t\t--><a> {{! These aren't real links, used to use theme colors }}\n\t\t\t\t\t\t{{#tl}}Include out of stock{{\/tl}}\n\t\t\t\t\t<\/a>\n\t\t\t\t<\/label>\n\t\t\t<\/li>\n\t\t<\/ul>\n\t<\/form>\n<\/li>\n",
		'search/filter/search-filter': "<li class=\"wsite-search-filter\">\n\t<h3>{{filter_name}}<\/h3>\n\t<ul class=\"wsite-search-filter-entries\">\n\t\t{{#filters}}\n\t\t\t<li style=\"{{style}}\">\n\t\t\t\t<a data-filter=\"{{filter_data}}\" href=\"{{url}}{{query_string}}\" {{#active}}class=\"active\"{{\/active}}>\n\t\t\t\t\t{{filter_name}}\n\t\t\t\t\t<span class=\"count\">(<span class=\"count-inner\">{{count}}<\/span>)<\/span>\n\t\t\t\t<\/a>\n\t\t\t<\/li>\n\t\t{{\/filters}}\n\t<\/ul>\n<\/li>\n",
		'search/filter/search-filters': "<ul id=\"wsite-search-sidebar\">\n\t{{#filters}}\n\t\t{{{.}}}\n\t{{\/filters}}\n\t{{#facets}}\n\t\t{{{.}}}\n\t{{\/facets}}\n<\/ul>\n",
		'search/search-results-list-items': "{{#has_product_results}}\n\t{{> search\/results\/product-group}}\n{{\/has_product_results}}\n\n{{#page_results}}\n\t{{> search\/results\/normal}}\n{{\/page_results}}\n\n{{#no_results}}\n\t{{> search\/results\/empty}}\n{{\/no_results}}\n\n{{#error_result}}\n\t{{> search\/results\/error}}\n{{\/error_result}}\n",
		'search/results/product-group': "<li id=\"wsite-search-product-result-section\">\n\t<h3>{{#tl}}Products{{\/tl}}<\/h3>\n\t<ul id=\"wsite-search-product-results\" class=\"clearfix\">\n\t\t{{#products}}\n\t\t\t{{> search\/results\/product}}\n\t\t{{\/products}}\n\t<\/ul>\n<\/li>",
		'search/results/product': "<li class=\"wsite-search-product-result\">\n\t<a href=\"{{url}}\">\n\t\t<div class=\"wsite-search-product-image-container\" style=\"background-image:url({{image_url}})\" title=\"{{title}}\">\n\t\t<\/div>\n\t\t<span class=\"wsite-search-product-name\" title=\"{{title_html}}\">{{{title_html}}}<\/span>\n\t<\/a>\n\t<span class=\"wsite-search-product-price\">\n\t\t{{#high_price_number}}\n\t\t\t<span class=\"wsite-search-product-price-low\">\n\t\t\t\t{{{currency_html}}}{{low_price_number}}\n\t\t\t<\/span>\n\t\t\t - \n\t\t\t<span class=\"wsite-search-product-price-high\">\n\t\t\t\t{{{currency_html}}}{{high_price_number}}\n\t\t\t<\/span>\n\t\t{{\/high_price_number}}\n\t\t{{^high_price_number}}\n\t\t\t<span class=\"wsite-search-product-price-low\">\n\t\t\t\t{{{currency_html}}}{{low_price_number}}\n\t\t\t<\/span>\n\t\t{{\/high_price_number}}\n\t<\/span>\n<\/li>\n",
		'search/results/normal': "<li>\n\t<a href=\"{{url}}\">\n\t\t<h3>\n\t\t\t{{#title_html}}\n\t\t\t\t{{{title_html}}}\n\t\t\t{{\/title_html}}\n\t\t\t{{^title_html}}\n\t\t\t\t{{#tl}}(No title){{\/tl}}\n\t\t\t{{\/title_html}}\n\t\t<\/h3>\n\t<\/a>\n\t<p>{{{content_html}}}<\/p>\n<\/li>\n",
		'search/results/empty': "<li class=\"no-results\">\n\t<p>{{#tl}}No results found for <strong>{{query}}<\/strong>.{{\/tl}}<\/p>\n<\/li>\n",
		'search/results/error': "<li class=\"no-results\">\n\t<p>{{#tl}}An error has occured <strong>{{error}}<\/strong>.{{\/tl}}<\/p>\n<\/li>\n",
		'search/core-pagination-list': "<ol id=\"wsite-search-pagenav\">\n\t{{#pagination_items}}\n\t\t{{> search\/pagination-item}}\n\t{{\/pagination_items}}\n<\/ol>",
		'search/pagination-item': "{{!\n\tNOTE: if an ellipsis is being displayed, there won't be an anchor tag and only the label will be displayed.\n}}\n\n<li>\n\t{{#url}}\n\t\t<a\n\t\t\t{{#is_active}}class=\"active\"{{\/is_active}}\n\t\t\t{{#is_disabled}}class=\"disabled\"{{\/is_disabled}}\n\t\t\thref=\"{{url}}\"\n\t\t\t>\n\t{{\/url}}\n\n\t\t{{text}}\n\n\t{{#url}}\n\t\t<\/a>\n\t{{\/url}}\n<\/li>\n",
	'': null // handle the trailing comma
};
delete Weebly.templates[''];